# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waxon < Formula
  desc "Vim-modal Spotify terminal client"
  homepage "https://github.com/danfry1/waxon"
  version "1.1.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danfry1/waxon/releases/download/v1.1.0/waxon_1.1.0_darwin_amd64.tar.gz"
      sha256 "ed73c70903470376ffb36a233dd7730ff4a1f508e7faff3c05b2e34ac262780c"

      define_method(:install) do
        bin.install "waxon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danfry1/waxon/releases/download/v1.1.0/waxon_1.1.0_darwin_arm64.tar.gz"
      sha256 "9656ed5a051cc16cf01ef05ffc0d25bd6d8d1b26d4f1deb1370c6866f8b8c2b7"

      define_method(:install) do
        bin.install "waxon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danfry1/waxon/releases/download/v1.1.0/waxon_1.1.0_linux_amd64.tar.gz"
      sha256 "1b95180ed652285910e4bbd490042c195ef195f8ca80aa6d6a274f9b36a476ca"
      define_method(:install) do
        bin.install "waxon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danfry1/waxon/releases/download/v1.1.0/waxon_1.1.0_linux_arm64.tar.gz"
      sha256 "dd21af54fc2f84cd04ee3e1e736024058845eab94ee3eb537edda83bca5fce44"
      define_method(:install) do
        bin.install "waxon"
      end
    end
  end

  test do
    system bin/"waxon", "version"
  end
end
