# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waxon < Formula
  desc "Vim-modal Spotify terminal client"
  homepage "https://github.com/danfry1/waxon"
  version "1.0.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danfry1/waxon/releases/download/v1.0.1/waxon_1.0.1_darwin_amd64.tar.gz"
      sha256 "9016dd95210f253211ed4135fdae55dae86ebff2f4d2490b8e53eaf7841b3c76"

      define_method(:install) do
        bin.install "waxon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danfry1/waxon/releases/download/v1.0.1/waxon_1.0.1_darwin_arm64.tar.gz"
      sha256 "bdde302920e632f98f3447a380019965855f985c2f7e690283ecc5e62298c1c7"

      define_method(:install) do
        bin.install "waxon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danfry1/waxon/releases/download/v1.0.1/waxon_1.0.1_linux_amd64.tar.gz"
      sha256 "8890f1c16b9089cf4ee9530e82e1ddd455130cb28e57821c14bb100ef66b74bc"
      define_method(:install) do
        bin.install "waxon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danfry1/waxon/releases/download/v1.0.1/waxon_1.0.1_linux_arm64.tar.gz"
      sha256 "1ba318969f3e812f736ce492312483d42df8f43569a522857d662f20c8d57900"
      define_method(:install) do
        bin.install "waxon"
      end
    end
  end

  test do
    system bin/"waxon", "version"
  end
end
