# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waxon < Formula
  desc "Vim-modal Spotify terminal client"
  homepage "https://github.com/danfry1/waxon"
  version "1.0.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danfry1/waxon/releases/download/v1.0.0/waxon_1.0.0_darwin_amd64.tar.gz"
      sha256 "985c16e9440aaf123683d2f160dcf1bc52f44ceeef70578048dbe8cc49c9bd82"

      define_method(:install) do
        bin.install "waxon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danfry1/waxon/releases/download/v1.0.0/waxon_1.0.0_darwin_arm64.tar.gz"
      sha256 "ca199ad45f8c099c67eb82ac622a6c2f3fde8578fc440d1fe3a73c20e922df03"

      define_method(:install) do
        bin.install "waxon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danfry1/waxon/releases/download/v1.0.0/waxon_1.0.0_linux_amd64.tar.gz"
      sha256 "1a5e43c867092eb3ac4ea3f0d58ca56d9a84531ec4f09fcd43ece035c3116ea5"
      define_method(:install) do
        bin.install "waxon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danfry1/waxon/releases/download/v1.0.0/waxon_1.0.0_linux_arm64.tar.gz"
      sha256 "9b6f5e6cf133a34e78c1652dd062ad821fd619c65635b8c0366d9ae9b0cc0027"
      define_method(:install) do
        bin.install "waxon"
      end
    end
  end

  test do
    system bin/"waxon", "version"
  end
end
