# typed: false
# frozen_string_literal: true

# This file is generated by the release workflow. DO NOT EDIT.
class WordleTui < Formula
  desc "Beautiful terminal word-guessing game built with ratatui"
  homepage "https://github.com/danfry1/wordle-tui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danfry1/wordle-tui/releases/download/v0.1.0/wordle-tui_0.1.0_darwin_amd64.tar.gz"
      sha256 "223f80e843cb0f60beb82975cf7aff71f96cb931a33b333eccef253ab84f1e5f"

      def install
        bin.install "wordle-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danfry1/wordle-tui/releases/download/v0.1.0/wordle-tui_0.1.0_darwin_arm64.tar.gz"
      sha256 "ab12b240ad3f85f205cbae7e0bbb87bdc9fde34c79701c4da1827bba2d6e0ce0"

      def install
        bin.install "wordle-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danfry1/wordle-tui/releases/download/v0.1.0/wordle-tui_0.1.0_linux_amd64.tar.gz"
      sha256 "82cc33a3c9b90147e57ebcfba9acd604901195c2f0eb5e61de8a4e88f575a5b7"

      def install
        bin.install "wordle-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danfry1/wordle-tui/releases/download/v0.1.0/wordle-tui_0.1.0_linux_arm64.tar.gz"
      sha256 "5d62cf12886167aa00e9bb893969ea0a1e61bae44f690ce72c13c6ae7a742b91"

      def install
        bin.install "wordle-tui"
      end
    end
  end

  test do
    assert_match "wordle-tui #{version}", shell_output("#{bin}/wordle-tui --version")
  end
end
