# This file was generated by GoReleaser. DO NOT EDIT.
cask "waxon" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "5e9fec2d71bcd4ee3b9a28bc1204e519e88339ef77c279eb6d2eb11cfb207b4e"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d7a595fc107cda0ac96c8ffea8296b6b71d69afba3bd05973d8b5085c370bfc"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "46ef0e999a660a05d1e204f4682e720f63e68af49540f652066d5724ef18624d"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d146fee6560fcb9e32637275c1d25a51748b4d2183d8930ae56c6ab380f3abf7"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "waxon"
  desc "Vim-modal Spotify terminal client"
  homepage "https://github.com/danfry1/waxon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waxon"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/waxon"]
    end
  end

  # No zap stanza required

end
