# This file was generated by GoReleaser. DO NOT EDIT.
cask "waxon" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/waxon"]
    end
  end

  version "1.8.1"

  on_macos do
    on_arm do
      sha256 "a3a901421b7d8f8b93127e27895f30ecaede76669a07c2e08607eb6bebada725"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5401e59e82bea3796be8fe7890d9ca2dc71942c90ae455f4f3ed354db98a5ea0"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0d113e2ad185421f84259c6a424ff41e9ac2b17803112c126cbf2d68737e984e"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8ad2c72cb1f5f9fbf86fc876a24fd653ac681003e7d0d66e0ade4c962456f438"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_linux_amd64.tar.gz"
    end
  end

  name "waxon"
  desc "Vim-modal Spotify terminal client"
  homepage "https://github.com/danfry1/waxon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waxon"

  # No zap stanza required
end
