# This file was generated by GoReleaser. DO NOT EDIT.
cask "waxon" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "b867a790c662bad96875aa2cfb27a807c5f8f534961f30f2251a4e909b1551f8"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ab057d0391bdd86c1987a0a3aabe1817e05968bd01db66b67c56346701489ae"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b25dc8b91bad9f41881e2f84abe856f8fd4ad98c2fd3f219f84a1c5cea8ecdc5"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "17c69c043ceee0790f70fca5938eef08b0dad0bcf695f50c7e5fce2ce7c64d17"
      url "https://github.com/danfry1/waxon/releases/download/v#{version}/waxon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "waxon"
  desc "Vim-modal Spotify terminal client"
  homepage "https://github.com/danfry1/waxon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waxon"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/waxon"]
    end
  end

  # No zap stanza required

end
